version: '3.8'

services:
  redis:
    image: redis:7-alpine
    env_file:
      - docker.env
    container_name: ecommerce-redis
    command: redis-server --requirepass projectleather --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "projectleather", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network

  minio:
    image: minio/minio:latest
    container_name: ecommerce-object-storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ecommerce-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ecommerce-rabbitmq
    ports:
      - "5672:5672"   # Spring Boot və n8n-in mesaj göndərəcəyi əsas port
      - "15672:15672" # Sənin üçün vizual İdarəetmə Paneli (Dashboard) portu
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network

volumes:
  minio_data:
    driver: local
  redis-data:
    driver: local
  rabbitmq_data: # RabbitMQ üçün yaddaş həcmi
    driver: local

networks:
  ecommerce-network:
    driver: bridge
