server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # ✅ Səhifəni yeniləyəndə (F5) 404 xətasının qarşısını alan əsas sətir:
        try_files $uri $uri/ /index.html;
    }

    # Statik faylların keşlənməsi (Performans üçün)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|mov|mp4)$ {
        root   /usr/share/nginx/html;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}