spring:
  application:
    name: Aiatelye

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      minimum-idle: 3
      maximum-pool-size: 6
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 60000

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 6MB
      max-request-size: 30MB

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_username}
    password: ${RABBITMQ_password}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 3
          max-interval: 10s

server:
  port: 8080

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ADMIN}
  secret-key: ${SECRET_ADMIN}
  bucket: ai-atelye-storage
  image:
    allowed-extensions: jpg,jpeg,png,webp
    max-size-mb: 5
  folders:
    product: products
    leather: leather-textures
    ai: ai-renders

ai:
  callback:
    secret: ${AI_CALLBACK_SECRET:my-super-secret-key-12345}

data:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    timeout: 6000ms

cache:
  redis:
    account:
      ttl: 120
    price:
      ttl: 12
    product-list:
      ttl: 30
    product-detail:
      ttl: 1440
    leather:
      ttl: 10
    grade:
      ttl: 60
    orderIdempotency:
      ttl: 30
    design:
      ttl: 86400
      generating:
        ttl: 300
      popular:
        ttl: 3600